#!/bin/bash

echo "Do you want to install all dependency? [Y/n] > "
read all

export PATH=$PATH:/usr/local/bin/

if [ "$all" != "Y" ];then
    echo "Install Python2.7?[Y/n]> "
    read lib
fi
if [ "$all" != "Y" ] || [ "$lib" = "Y" ] ; then
    #install python 2.7.6
    sudo yum -y install bzip2-devel
    sudo yum -y install zlib-devel
    sudo yum -y install sqlite-devel
    sudo yum -y install gccgcc-c++.x86_64 compat-gcc-34-c++.x86_64 openssl-devel.x86_64 zlib*.x86_64 wget make setuptool
    sudo yum groupinstall -y development
    wget http://www.python.org/ftp/python/2.7.6/Python-2.7.6.tar.xz
    xz -d Python-2.7.6.tar.xz
    tar -xvf Python-2.7.6.tar
    pushd "Python-2.7.6"
    ./configure --prefix=/usr/local
    make
    sudo make altinstall
    popd

    rm -rf Python-2.7.6
    rm -rf Python-2.7.6.tar.xz

    #update symbolic link
    sudo ln -s /usr/local/bin/python2.7 /usr/local/bin/python

    #install setup tool 
    wget --no-check-certificate https://pypi.python.org/packages/source/s/setuptools/setuptools-1.4.2.tar.gz
    tar -xvf setuptools-1.4.2.tar.gz
    pushd "setuptools-1.4.2"
    python2.7 setup.py install
    popd

    rm -rf setuptools-1.4.2.tar.gz
    rm -rf setuptools-1.4.2

    #install pip
    curl https://raw.github.com/pypa/pip/master/contrib/get-pip.py | python2.7 -
    pip install pip --upgrade
fi

if [ "$all" != "Y" ];then
    echo "Install ZeroMQ?[Y/n] > "
    read lib
fi
if [ "$all" != "Y" ] || [ "$lib" = "Y" ] ; then
    yum  -y install uuid-devel
    wget http://download.zeromq.org/zeromq-3.2.4.tar.gz
    tar xzvf zeromq-3.2.4.tar.gz
    pushd "zeromq-3.2.4" 
    ./configure
    make
    make install
    echo /usr/local/lib > /etc/ld.so.conf.d/local.conf
    ldconfig
    popd

    rm -rf zeromq-3.2.4.tar.gz
    rm -rf zeromq-3.2.4
fi

if [ "$all" != "Y" ];then
    echo "Install mongodb?[Y/n] > "
    read lib
fi
if [ "$all" != "Y" ] || [ "$lib" = "Y" ] ; then
    #mongodb
    sudo cp mongodb.repo /etc/yum.repos.d/
    yum -y install mongo-10gen mongo-10gen-server
    #start mongod
    service mongod start
    chkconfig mongod on
fi

if [ "$all" != "Y" ];then
    echo "Install dateutil?[Y/n] > "
    read lib
fi
if [ "$all" != "Y" ] || [ "$lib" = "Y" ] ; then
    sudo yum -y install python-dateutil
fi


if [ "$all" != "Y" ];then
    echo "Install pyparsing?[Y/n] > "
    read lib
fi
if [ "$all" != "Y" ] || [ "$lib" = "Y" ] ; then
    pip install pyparsing
fi

if [ "$all" != "Y" ];then
    echo "Install pyzmq?[Y/n] > "
    read lib
fi
if [ "$all" != "Y" ] || [ "$lib" = "Y" ] ; then
    pip install pyzmq
fi

if [ "$all" != "Y" ];then
    echo "Install bottle?[Y/n] > "
    read lib
fi
if [ "$all" != "Y" ] || [ "$lib" = "Y" ] ; then
    pip install bottle
fi

if [ "$all" != "Y" ];then
    echo "Install tornado?[Y/n]> "
    read lib
fi
if [ "$all" != "Y" ] || [ "$lib" = "Y" ] ; then
    pip install tornado
fi


if [ "$all" != "Y" ];then
    echo "Install pymongo?[Y/n] > "
    read lib
fi
if [ "$all" != "Y" ] || [ "$lib" = "Y" ] ; then
    pip install pymongo
fi

pushd "NetworkSearch2"
cp configTemplate.cfg config.cfg
popd
