#!/bin/bash
#NetworkSearch.sh $@

# get current working directory
_pwd=`pwd`

# export the python path
export PYTHONPATH=$_pwd
python_args="start"


echo "start Query processing module..."
python "$_pwd/NetworkSearch2/manager.py" $python_args &
sleep 1

echo "start Indexing module..."
python "$_pwd/NetworkSearch2/IndexingSubsystem/indexManager.py" $python_args  &
sleep 1

echo "start Sensor module..."
#sudo env PYTHONPATH=$_pwd 
python "$_pwd/NetworkSearch2/SensorSubsystem/sensorManager.py" $python_args  &
sleep 1

echo "start web module..."
nohup python "$_pwd/NetworkSearch2/web/web_server.py" $python_args  &
sleep 1

#echo "start node distance module..."
#nohup python "$_pwd/NetworkSearch2/nodes.py" $python_args  &
#sleep 1

echo "Done"

